POST http://localhost:8080/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEiLCJleHAiOjE3NDU5Mzc2MTYsInVzZXJfaWQiOjF9.SuL6QBVBeaig_9DK92kgQxS4vfoMoCodFBo55Q_qTr4

{
   "title": "Task 1 Title",
  "description": "This is test task 1",
  "complete": false,
   "priority": "low",
  "dueAt": "2025-05-01T10:00:00Z",
  "category": "social"
}