GET http://localhost:8080/tasks/category/Self%20Development
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2FzQGdtYWlsLmNvbSIsImV4cCI6MTc0NTQwODIwNywidXNlcl9pZCI6MX0.3fBV3v-dvBWvdVGowusPRHpNdr57ydxt47pk7TXo_90