GET http://localhost:8080/tasks?search=up&limit=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2FzQGdtYWlsLmNvbSIsImV4cCI6MTc0NTUxMTIyNiwidXNlcl9pZCI6MX0.TNtIj6RTKJNFx7l5eeoCh720ZPlKPSfgQLJhooq9ixw