GET http://localhost:8080/tasks?limit=3&category=Social&page=3&order=desc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2FzQGdtYWlsLmNvbSIsImV4cCI6MTc0NTUwODk4MSwidXNlcl9pZCI6MX0.z8z1cB4r3uRO5VuCs4sF0Mw1H88kskzm6HdRiUy5M9U