GET http://localhost:8080/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2FzQGdtYWlsLmNvbSIsImV4cCI6MTc0NDkxNDUxOCwidXNlcl9pZCI6MX0.tFKwg9KPPaMJKPM_IPQNFYFM-OR6PW0t6LIsUEQmIlE