GET http://localhost:8080/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsaWNlQGdtYWlsLmNvbSIsImV4cCI6MTc0NTY5OTE4OSwidXNlcl9pZCI6M30.sm2V7afYhkgAMjhP91w2QPgGQ81XDSd3gVrIFQgDAzc